// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz_H2rQIWbvbJ6RXj6Ehk0owYQqOdZYeI',
    appId: '1:947720252627:web:93bcdae612fe82203d7826',
    messagingSenderId: '947720252627',
    projectId: 'chat-room-project-945c2',
    authDomain: 'chat-room-project-945c2.firebaseapp.com',
    storageBucket: 'chat-room-project-945c2.appspot.com',
    measurementId: 'G-2ZB6F8EZLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTePsDgN0eDIL6S1MVs183Ct2Rw_RLepk',
    appId: '1:947720252627:android:15888ebf0ad3ccec3d7826',
    messagingSenderId: '947720252627',
    projectId: 'chat-room-project-945c2',
    storageBucket: 'chat-room-project-945c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEi8fnF2CjbclfEoud3hBPA5G3dJL30vg',
    appId: '1:947720252627:ios:d5dbae9c1e2c78533d7826',
    messagingSenderId: '947720252627',
    projectId: 'chat-room-project-945c2',
    storageBucket: 'chat-room-project-945c2.appspot.com',
    iosBundleId: 'com.example.chatRoomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEi8fnF2CjbclfEoud3hBPA5G3dJL30vg',
    appId: '1:947720252627:ios:9ab72cd1fdf7afb33d7826',
    messagingSenderId: '947720252627',
    projectId: 'chat-room-project-945c2',
    storageBucket: 'chat-room-project-945c2.appspot.com',
    iosBundleId: 'com.example.chatRoomApp.RunnerTests',
  );
}
